export enum Routes {
  LOGIN = 'Login',
  REGISTER = 'Register',
  HOME = 'Home',
  ADDRESS = 'Address',
  CART = 'Cart',
  CHECKOUT = 'CheckOut',
  PRODUCTS = 'Products',
  PRODUCT_DETAILS = 'ProductDetails',
  PAYMENT = 'Payment',
  CONFIRMATION = 'Confirmation', 
  ORDERS = 'Orders',
  ORDER_DETAIL = 'OrderDetail',
  RETURN = 'Return',
}